/*******************************************************************************
© Copyright 2003. The U.S. Government, as Represented by the Administrator of
the National Aeronautics and Space Administration (NASA). All rights reserved.
Includes content licensed from the U.S. Government, National Aeronautics and
Space Administration under United States Copyright Registration Numbers
V3503D364 and V3482D344.
© 2008-2015 NPSS® Consortium, www.NPSSConsortium.org/AllRightsReserved
*******************************************************************************/

/*******************************************************************************
NPSS® software and related documentation is export controlled with an Export
Control Classification Number(ECCN) of 9D991, controlled for Anti-Terrorism
reasons, under U.S. Export Administration Regulations 15 CFR 730-774. It may
not be transferred to a country checked under anti-terrorism on the Commerce
Country Chart structure or to foreign nationals of those countries in the U.S.
or abroad without first obtaining a license from the Bureau of Industry and
Security, United States Department of Commerce. Violations are punishable by
fine, imprisonment, or both.
*******************************************************************************/

// Make GasTbl the default thermopackage
// #ifndef THERMO
// #define THERMO GasTbl
// #endif

//include the power train components 
//#include "PTE_Viewer.view"
#include "npssel.view"
#include "npssel_runtime.view"

// add in electric port
#include "ElectricPort.prt"
#include "InterpretedPort.int"

MODELNAME = "battery_test";

//model file
#include "model/battery_test.mdl"

/************************
On design
************************/
setOption("switchDes","DESIGN"); 
autoSolverSetup();
//solver.solutionMode = "ONE_PASS";

solver.maxIterations=500;
solver.maxJacobians=500;
cout << endl << solver.dependentNames << endl << solver.independentNames << endl;

// Constant power load 14 W for Case 0 and 1
run();
BFPrintOutput();
page.display();  // output data to out file

/************************
Off design
************************/

setOption("switchDes","OFFDESIGN"); 
autoSolverSetup();

CASE++; run();
BFPrintOutput();
page.display(); 

CLoad.Pdemand = -14./1000.; // Charge the battery roughly at 1 C (14 W)

// Constant power load -14 W for Case 2
CASE++; run();
BFPrintOutput();
page.display();
