/*******************************************************************************
© Copyright 2003. The U.S. Government, as Represented by the Administrator of
the National Aeronautics and Space Administration (NASA). All rights reserved.
Includes content licensed from the U.S. Government, National Aeronautics and
Space Administration under United States Copyright Registration Numbers
V3503D364 and V3482D344.
© 2008-2015 NPSS® Consortium, www.NPSSConsortium.org/AllRightsReserved
*******************************************************************************/

/*******************************************************************************
NPSS® software and related documentation is export controlled with an Export
Control Classification Number(ECCN) of 9D991, controlled for Anti-Terrorism
reasons, under U.S. Export Administration Regulations 15 CFR 730-774. It may
not be transferred to a country checked under anti-terrorism on the Commerce
Country Chart structure or to foreign nationals of those countries in the U.S.
or abroad without first obtaining a license from the Bureau of Industry and
Security, United States Department of Commerce. Violations are punishable by
fine, imprisonment, or both.
*******************************************************************************/

/*******************************************************************************
This example is intended to test the aero cable sizing code. It has 2 subsystems,
an AC one and a DC one. Both subsystems include a cable, with some voltage across
them. The input side of the cables see a constant voltage, and the output side
voltages are independents intended to be varied to achieve a constant power
through the cable and desired power factor as well. The system is run to design
the cables, and then run off design at the same point, as well as a point with
increased power to see how variables change
*******************************************************************************/

// add in electric port
#include "ElectricPort.prt"
#include "InterpretedPort.int"

//include viewers
#include "npssel.view"
#include "npssel_runtime.view"

// select model
#include "cable_thermal_test.mdl"
solver.maxIterations = 5000;
solver.maxJacobians = 1000;

setThermoPackage( "GasTbl" );

Element FlowStart fs_coolant{
 // Fl_O.comp = "CEAT";
 Tt = 518.0;
 Pt = 14.504;
 W=1.0;
}

ACCable {
    // Initial guesses
    Ireal = 1100;
    Iimag = 0;

    // Subelement
    Subelement EThermalMass S_eThermMass {
        Cp = 1.0e-2;
    }
}
// setOption("switchThermPort", "TRUE");

// Create a magic thermal output port that represents the heat extraction
// from the cable.
Element ThermalDuct TMS{
  switchQ = "CALCULATE";
  // switchDP = "INPUT";
  // Q_in = 30;
  dPqP_dmd = 0.01;
  Subelement ThermalVolume S_Q {
      eff = 0.8;
      Volume = 100;
  }
}
setOption("switchThermPort", "TRUE");

Element FlowEnd fe_coolant{
	void postexecute(){
	  //cerr << "comp is " << Fl_I.comp << endl;
	}
}

linkPorts("fs_coolant.Fl_O","TMS.Fl_I", "FC1");
linkPorts("TMS.Fl_O","fe_coolant.Fl_I", "FC2");

linkPorts("TMS.Q_O","ACCable.Q_I","Q1");
// solverSequence = { "TD", "Load" , "fe_coolant" };
solverSequence = { "fs_coolant", "ACS", "TMS", "ACCable", "fe_coolant" };
setOption("switchDes", "DESIGN");


autoSolverSetup();

cout << "--- On Design ---" << endl;
cout << solverSequence << endl;
cout << endl << solver.dependentNames << endl << solver.independentNames << endl;

cout << "CASE #" << CASE++ << endl;
run();
cout << "AC R+jX = " << ACCable.R << "+j" << ACCable.L*(2*PI*ACCable.EP_I.frequency);
cout << "   ACVout = " << ACS.Vreal << "+j" << ACS.Vimag;
cout << " \t ACPin = " << ACS.EP_O.S.r << "+j" << ACS.EP_O.S.j;
cout << " \t\t ACPout = " << ACS.EP_I.S.r << "+j" << ACS.EP_I.S.j;
cout << " \t PF at cable input = " << cos(ACS.EP_O.S.phase) << endl;

cout << "AC: dV_calc =" << ACCable.Vreal_drop;
cout << "+j" << ACCable.Vimag_drop;
cout << "\t  dV_meas =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r);
cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j);
cout << " \t dV_error =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r+ACCable.Vreal_drop);
cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j+ACCable.Vimag_drop);
cout << " \t\t\t I =" << ACCable.EP_O.I.r;
cout << "+j" << ACCable.EP_O.I.j  << endl;
        cout << "TMS.Q_O.HeatTransferRate = " << TMS.Q_O.HeatTransferRate << ", ";
        cout << "TMS.Q_O.MassTemp = " << TMS.Q_O.MassTemp << endl;




real OD_en=0;
if (OD_en==1){
  cout << "--- Off Design ---" << endl;
  setOption("switchDes","OFFDESIGN");
  // For off design, stop varying the source.
  ACS.ind_Vimag.autoSetup = FALSE;
  ACS.dep_PF.autoSetup    = FALSE;
  ACS.ind_Vreal.autoSetup = FALSE;
  ACS.dep_Power.autoSetup = FALSE;
  autoSolverSetup();
  cout << solverSequence << endl;
  cout << endl << solver.dependentNames << endl << solver.independentNames << endl;

  // Run off-design, same inputs
  cout << "CASE #" << CASE++ << endl;
  run();
  cout << "AC R+jX = " << ACCable.R << "+j" << ACCable.L*(2*PI*ACCable.EP_I.frequency);
  cout << "   ACVout = " << ACS.Vreal << "+j" << ACS.Vimag;
  cout << " \t ACPin = " << ACS.EP_O.S.r << "+j" << ACS.EP_O.S.j;
  cout << " \t\t ACPout = " << ACS.EP_I.S.r << "+j" << ACS.EP_I.S.j;
  cout << " \t PF at cable input = " << cos(ACS.EP_O.S.phase) << endl;

  cout << "AC: dV_calc =" << ACCable.Vreal_drop;
  cout << "+j" << ACCable.Vimag_drop;
  cout << "   dV_meas =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r);
  cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j);
  cout << " \t dV_error =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r+ACCable.Vreal_drop);
  cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j+ACCable.Vimag_drop);
  cout << " \t\t\t I =" << ACCable.EP_O.I.r;
  cout << "+j" << ACCable.EP_O.I.j  << endl;
          cout << "TMS.Q_O.HeatTransferRate = " << TMS.Q_O.HeatTransferRate << ", ";
          cout << "TMS.Q_O.MassTemp = " << TMS.Q_O.MassTemp << endl;


  // Set up transient run
  solver.defaultDxLimit = 0.001;
  solver.maxIterations=3000;
  solver.maxJacobians=3000;
  setOption("switchDes","OFFDESIGN");

  setOption( "solutionMode", "TRANSIENT");
  transient.stopTime = 15;
  transient.baseTimeStep = .01;
  transient.setup();
  initializeHistory();
  autoSolverSetup();

  // Run off-design, increase power by increasing voltage drop (decrease voltage on output side of cable).
  ACS.Vreal *= 0.9999;
  ACS.Vimag /= 0.9;

  // Transient data out to a CSV file for plotting
  OutFileStream transientCSVStream { filename = "output/T_transient.csv"; }

  // Write the CSV headers
  transientCSVStream << "Q_loss,";
  transientCSVStream << "HeatTransferRate,";
  transientCSVStream << "MassTemp,";
  transientCSVStream << "CASE,";
  transientCSVStream << "time" << endl;

  void csvTransientPrint()
  {
      transientCSVStream << ACCable.Q_loss << ", ";
      transientCSVStream << TMS.Q_O.HeatTransferRate << ", ";
      transientCSVStream << TMS.Q_O.MassTemp-458.67 << ", ";
      transientCSVStream << CASE << ", ";
      transientCSVStream << time << endl;

      cout << "CablePowerDissipated (BTU/s), "  << ACCable.Q_loss << ", ";
      cout << "HeatTransferRate (BTU/s), "  << TMS.Q_O.HeatTransferRate << ", ";
      cout << "MassTemp (deg F), "          << TMS.Q_O.MassTemp-458.67 << ", ";
      cout << "CASE, "              << CASE << ", ";
      cout << "time, "              << time << endl;
  }

  postsolverSequence = { "csvTransientPrint" };



  //cout << "CASE #" << CASE++ << " -- increased power" << endl;
  run();
  //cout << "AC R+jX = " << ACCable.R << "+j" << ACCable.L*(2*PI*ACCable.EP_I.frequency);
  //cout << "   ACVout = " << ACS.Vreal << "+j" << ACS.Vimag;
  //cout << " \t ACPin = " << ACS.EP_O.S.r << "+j" << ACS.EP_O.S.j;
  //cout << " \t\t ACPout = " << ACS.EP_I.S.r << "+j" << ACS.EP_I.S.j;
  //cout << " \t PF at cable input = " << cos(ACS.EP_O.S.phase) << endl;
  //
  //cout << "AC: dV_calc =" << ACCable.Vreal_drop;
  //cout << "+j" << ACCable.Vimag_drop;
  //cout << "\t  dV_meas =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r);
  //cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j);
  //cout << " \t dV_error =" << ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r+ACCable.Vreal_drop);
  //cout << "+j" << ACCable.EP_I.VLN.j - (ACCable.EP_O.VLN.j+ACCable.Vimag_drop);
  //cout << " \t\t\t I =" << ACCable.EP_O.I.r;
  //cout << "+j" << ACCable.EP_O.I.j  << endl;
  //        cout << "TMS.Q_O.HeatTransferRate = " << TMS.Q_O.HeatTransferRate << ", ";
  //        cout << "TMS.Q_O.MassTemp = " << TMS.Q_O.MassTemp << endl;


  // Run back to the original operating point.
  ACS.Vreal /= 0.9999;
  ACS.Vimag *= 0.9;
  transient.stopTime = 30;
  run();

}
